name: Generate GitHub Trophy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate-trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: EndlessLiu
          token: ${{ secrets.GITHUB_TOKEN }}
          file: assets/trophy.svg
          theme: darkhub
          max-cols: 7
          max-rows: 2
          margin-width: 10
          margin-height: 10
          no-background: true
          no-frame: true

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/trophy.svg

          git commit -m "Update GitHub trophy" || exit 0
          git push
